name: bld_test
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  country_code_picker: ^1.6.0
  flutter_animation_progress_bar: ^1.0.5
  shared_preferences: ^0.5.12+2
  pin_code_fields: ^6.0.0
  animations: ^1.1.2
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  transformer_page_view: ^0.1.6
  firebase_database:
  firebase_storage:
  cloud_firestore:
  fluttertoast: ^7.1.1
  cached_network_image: ^2.3.3
  firebase_crashlytics: ^0.2.1+1
  image_picker: ^0.6.7+12



  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - asset/images/background.png
   - asset/image.png
   - asset/unselected.png
   - asset/checking.png
   - asset/images/dashboard_bg.png
   - asset/images/dash_gradient.png
   - asset/images/brain.png
   - asset/images/myservice_grad.png
   - asset/images/myservice_bg.png
   - asset/images/gender.png
   - asset/images/medal.png
   - asset/images/test_grad.png
   - asset/images/service_grad.png
   - asset/images/agenda.png
   - asset/images/profile.png
   - asset/images/trophy.png


  fonts:
    - family : MontserratAlternates
      fonts :
        - asset: fonts/montserrat_alternate/MontserratAlternates-BlackItalic.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-Black.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-Bold.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-BoldItalic.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-ExtraBold.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-ExtraBoldItalic.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-ExtraLight.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-ExtraLightItalic.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-Italic.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-Light.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-LightItalic.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-Medium.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-MediumItalic.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-Regular.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-SemiBold.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-SemiBoldItalic.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-Thin.ttf
        - asset: fonts/montserrat_alternate/MontserratAlternates-ThinItalic.ttf
    - family : Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Black.ttf
        - asset: fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: fonts/montserrat/Montserrat-Bold.ttf
        - asset: fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/montserrat/Montserrat-Italic.ttf
        - asset: fonts/montserrat/Montserrat-Light.ttf
        - asset: fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: fonts/montserrat/Montserrat-Medium.ttf
        - asset: fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/montserrat/Montserrat-Thin.ttf
        - asset: fonts/montserrat/Montserrat-ThinItalic.ttf
    - family : Cera Pro
      fonts :
        - asset : fonts/cera/Cera Compact Pro Black.otf
        - asset : fonts/cera/Cera Compact Pro Black Italic.otf
        - asset : fonts/cera/Cera Compact Pro Bold.otf
        - asset : fonts/cera/Cera Compact Pro Bold Italic.otf
        - asset : fonts/cera/Cera Compact Pro Light.otf
        - asset : fonts/cera/Cera Compact Pro Light Italic.otf
        - asset : fonts/cera/Cera Compact Pro Medium.otf
        - asset : fonts/cera/Cera Compact Pro Medium Italic.otf
        - asset : fonts/cera/Cera Compact Pro Regular.otf
        - asset : fonts/cera/Cera Compact Pro Regular Italic.otf
        - asset : fonts/cera/Cera Compact Pro Thin.otf
        - asset : fonts/cera/Cera Compact Pro Thin Italic.otf
        - asset : fonts/cera/Cera Pro Black.otf
        - asset : fonts/cera/Cera Pro Black Italic.otf
        - asset : fonts/cera/Cera Pro Bold.otf
        - asset : fonts/cera/Cera Pro Bold Italic.otf
        - asset : fonts/cera/Cera Pro Light.otf
        - asset : fonts/cera/Cera Pro Light Italic.otf
        - asset : fonts/cera/Cera Pro Medium.otf
        - asset : fonts/cera/Cera Pro Medium Italic.otf
        - asset : fonts/cera/Cera Pro Regular.otf
        - asset : fonts/cera/Cera Pro Regular Italic.otf
        - asset : fonts/cera/Cera Pro Thin.otf
        - asset : fonts/cera/Cera Pro Thin Italic.otf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
